name: GATE Action CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install sfml
      run: sudo apt-get install libsfml-dev
    - name: make
      run: make
    - name: make test
      run: make test
